mongodb:
  host: 'example.com'
  port: 27017
  username: 'trainr'
  password: 'trainr'
  authDB: 'trainr'
  dataDB: 'trainr'
blockRemoval:
  interval: 5
  warningStateDuration: 20
  warningMaterial: REDSTONE_BLOCK
playerTeleportation:
  interval: 5
spawn:
  location:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 64
    z: 0
    pitch: 0
    yaw: 0
  offset:
    x: 10
    z: 0