mongodb:
  host: 'example.com'
  port: 27017
  username: 'trainr'
  password: 'trainr'
  authDB: 'trainr'
  dataDB: 'trainr'
blockRemoval:
  interval: 20
  warningOffset: 5000
  deletionOffset: 6500
  warningMaterial: REDSTONE_BLOCK
location:
  spawn:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 64
    z: 0
    pitch: 0
    yaw: 0
  offset:
    x: 10
    z: 0