mongodb:
  connectionURI: 'mongodb://trainr:trainr@example.com/trainr'
  database: 'trainr'
blockRemoval:
  interval: 5
  warningStateDuration: 20
  warningMaterial: REDSTONE_BLOCK
playerTeleportation:
  interval: 5
spawn:
  location:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 64
    z: 0
    pitch: 0
    yaw: 0
  offset:
    x: 10
    z: 0